//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STI> STIs { get; set; }
        public virtual DbSet<STK> STKs { get; set; }
    
        public virtual ObjectResult<ProcedureTest_Result> ProcedureTest(string malKodu, Nullable<int> baslangicTarihi, Nullable<int> bitisTarihi)
        {
            var malKoduParameter = malKodu != null ?
                new ObjectParameter("MalKodu", malKodu) :
                new ObjectParameter("MalKodu", typeof(string));
    
            var baslangicTarihiParameter = baslangicTarihi.HasValue ?
                new ObjectParameter("BaslangicTarihi", baslangicTarihi) :
                new ObjectParameter("BaslangicTarihi", typeof(int));
    
            var bitisTarihiParameter = bitisTarihi.HasValue ?
                new ObjectParameter("BitisTarihi", bitisTarihi) :
                new ObjectParameter("BitisTarihi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcedureTest_Result>("ProcedureTest", malKoduParameter, baslangicTarihiParameter, bitisTarihiParameter);
        }
    }
}
